### PR TITLE
add description, link to slack

### PR DESCRIPTION
**Pull request by josephholsten**

### CODE REVIEW

**Comment by zarry** [comment]
LGTM :+1: May want to consider adding something similar to the top of all cookbooks we manage.

**Comment by josephholsten** [comment]
@zarry was just going to ask the mongodb cookbook folks about that

**Comment by rex** [comment]
@josephholsten Done and done :) https://github.com/chef-brigade/mongodb-cookbook/commit/f6acf3c4a60cb861145534088633d5b469ffed2d

That said, though, I would really like to come up with a nice-looking standard template for READMEs. Something with a nice centered logo (that we should come up with), centered badges, and defined structure.

**Comment by josephholsten** [comment]
:+1: to a read me template. 

I'd love to develop a visual vocabulary for logos, something that both says eg "about mongodb" and "from chef brigade". Preferably without stretching food metaphors beyond the breaking point ;-)

**Comment by dblessing** [comment]
A template sounds good, can we ensure it's compatible with `knife-cookbook-doc`? https://github.com/realityforge/knife-cookbook-doc It's really the best tool to compile cookbook documentation. You could bake the logo and front-matter into the overview.md file.

**Comment by juliandunn** [comment]
:shipit:

**Comment by rex** [comment]
@dblessing Absolutely. Great idea. Being fancy takes a back seat to being interoperable. And if we can do both it's a big win :)

@josephholsten Coming up with food metaphors as we speak ;)

**Pull request merged**
