### PR TITLE
Describe membership roles

### PR DESCRIPTION
**Pull request by josephholsten**
#6 has started a general conversation about the roles and membership of the brigade. Here's a first pass at an "official" description.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
LGTM

I'd like to get access to Chef de partie, don't think I should be an owner.

**Comment by josephholsten** [comment]
@lamont-granquist welcome to the partie!

**Comment by dblessing** [comment]
:+1:

**Comment by zarry** [comment]
:+1:

**Comment by thommay** [comment]
LGTM. Please can I get Chef de Partie access too?

**Comment by juliandunn** [comment]
:+1: 

Next up we should write a doc describing how to transfer a cookbook into this org.

**Comment by lamont-granquist** [comment]
Yeah, I'm itching to make some comments on the ownership doc.

**Comment by rex** [comment]
:+1: I think this set of roles is perfectly sufficient for us moving forward. If we start growing and require additional teams/permission sets then we can cross that bridge when we come to it.

**Comment by rex** [comment]
As a side note, I think it would be valuable to include the names of the organization members and the roles that they currently occupy.

**Comment by lamont-granquist** [comment]
owners:  https://github.com/orgs/chef-brigade/teams/owners

partie-goers: https://github.com/orgs/chef-brigade/teams/chef-de-partie

**Comment by zuazo** [comment]
I think this is enough to get started :+1:

There is no need to list the members. GitHub already does that. Perhaps in the future if more specific roles are needed.

**Comment by juliandunn** [comment]
@josephholsten time to push the big green button?

**Pull request merged**
